# Keep rules for R8 **full mode** (android.enableR8.fullMode=true in gradle.properties).
#
# Two things are different in full mode and both bite here:
#   * `-keep class X` no longer implies keeping X's members. Anything reached by name needs
#     its members named too.
#   * A class R8 never sees allocated is assumed never instantiated, so anything the platform
#     or a native layer constructs has to be kept explicitly.
#
# Every rule below says which mechanism needs it. There is deliberately no blanket keep on
# com.lightphone.** — that would throw away the reason for turning this on.

# --------------------------------------------------------------------- crash readability
# Shake-to-report posts the stack trace into a GitHub issue. Without these a report reads
# `a.a.a(SourceFile)` and is worth nothing. Costs a few KB in the mapping-adjacent attributes.
-keepattributes SourceFile,LineNumberTable
-renamesourcefileattribute SourceFile
# Kotlin reflection-lite, coroutine debug names and generic signatures used by the JSON layer.
-keepattributes Signature,InnerClasses,EnclosingMethod,RuntimeVisibleAnnotations,AnnotationDefault

# --------------------------------------------------------------------- JNA (UniFFI's FFI layer)
# JNA maps Java types onto C by reflecting over field order and method signatures at runtime,
# and loads its own dispatch classes from the native library. Nothing calls these by name in
# Kotlin, so R8 sees them as dead.
-dontwarn java.awt.*
-keep class com.sun.jna.** { *; }
-keepclassmembers class * extends com.sun.jna.** { public *; }

# --------------------------------------------------------------------- UniFFI bindings
# Generated by uniffi-bindgen at build time. The Rust side calls back into these — including
# the callback-interface vtables, which are plain structs holding method pointers that R8 has
# no way to see being used.
-keep class com.lightphone.spotify.ffi.** { *; }

# --------------------------------------------------------------------- JNI entry points
# Resolved from C by exact class + method name. NativeInit sets the identity overrides after
# System.loadLibrary; PhonoAudioTrackSink is called on the Rust player's drain thread for every
# buffer, so a renamed method is silence rather than a crash.
-keep class com.lightphone.spotify.NativeInit { *; }
-keep class com.lightphone.spotify.audio.PhonoAudioTrackSink { *; }

# --------------------------------------------------------------------- Room
# Room resolves its generated implementation with Class.forName(<database>_Impl) and invokes
# the no-arg constructor. Full mode removes both the class and, separately, the constructor.
-keep class * extends androidx.room.RoomDatabase { <init>(); }
-dontwarn androidx.room.paging.**

# LibraryResourceConverter round-trips this enum through LibraryResource.valueOf(String), and
# the strings are already sitting in phono_library.db from previous builds. Renaming the
# constants would make every existing row unreadable.
-keepclassmembers enum com.lightphone.spotify.data.local.LibraryResource { *; }

# Same mechanism, different store: these three are written into SharedPreferences as
# `value.name` and read back by matching `it.name`, so the constant names are a persisted
# format. A rename does not crash — it silently resets the setting on every app update, which
# is worse.
-keepclassmembers enum com.lightphone.spotify.ui.light.ArtworkTreatment { *; }
-keepclassmembers enum com.lightphone.spotify.data.backend.BackendChoice { *; }
-keepclassmembers enum com.lightphone.spotify.podcast.PodcastRetention { *; }

# --------------------------------------------------------------------- kotlinx.serialization
# The plugin generates a `$serializer` object per @Serializable class, reached from the
# companion rather than from a call site R8 can trace. Field names themselves do not matter —
# every wire name is pinned with @SerialName — but the serializer objects do.
-if @kotlinx.serialization.Serializable class **
-keepclassmembers class <1> {
    static <1>$Companion Companion;
}
-if @kotlinx.serialization.Serializable class ** {
    static **$* *;
}
-keepclassmembers class <2>$<3> {
    kotlinx.serialization.KSerializer serializer(...);
}
-if @kotlinx.serialization.Serializable class ** {
    public static ** INSTANCE;
}
-keepclassmembers class <1> {
    public static <1> INSTANCE;
    kotlinx.serialization.KSerializer serializer(...);
}

# --------------------------------------------------------------------- Media3 session
# The session package is the cross-process surface: SystemUI and any other MediaController bind
# to it and exchange Parcelables and Bundles whose class names travel over the wire, and the
# legacy MediaSessionCompat interop resolves classes from a Bundle's class loader. media3-common
# is left to shrink normally — nothing outside the process names it. ExoPlayer, which is the
# reflective part of Media3, is not a dependency of this app at all.
-keep class androidx.media3.session.** { *; }

# --------------------------------------------------------------------- OkHttp
-dontwarn okhttp3.internal.platform.**
-dontwarn org.conscrypt.**
-dontwarn org.bouncycastle.**
-dontwarn org.openjsse.**
# Looked up by its own name to find the bundled public-suffix resource.
-keepnames class okhttp3.internal.publicsuffix.PublicSuffixDatabase

# --------------------------------------------------------------------- Guava (Media3's futures)
-dontwarn com.google.common.**
-dontwarn javax.annotation.**
-dontwarn org.checkerframework.**
-dontwarn sun.misc.Unsafe

# --------------------------------------------------------------------- Tink (EncryptedSharedPreferences)
# androidx.security's storage is Tink underneath, and Tink is a registry keyed by type-URL
# strings: key managers and their protos are found by string, not by call. Stripping one turns
# the Web API sign-in into an exception at first read, on a device, days after the build.
-keep class com.google.crypto.tink.** { *; }
-dontwarn com.google.crypto.tink.**
-dontwarn com.google.errorprone.annotations.**

# --------------------------------------------------------------------- CameraX + ML Kit (QR scan)
# ML Kit's bundled barcode model is loaded through GMS-internal shims that resolve
# implementation classes by name; CameraX instantiates its camera2 implementation from a
# string in its own config.
-keep class androidx.camera.** { *; }
-keep class com.google.mlkit.** { *; }
-keep class com.google.android.gms.internal.mlkit_vision_barcode.** { *; }
-keep class com.google.android.gms.internal.mlkit_vision_common.** { *; }
-dontwarn com.google.mlkit.**
-dontwarn com.google.android.gms.**

# --------------------------------------------------------------------- release logging
# proguard-android-optimize strips Log.d/v/i. These two carry the only diagnosis we get for a
# failed Spotify login, which happens on user devices and nowhere else.
-keepclassmembers class com.lightphone.spotify.ui.OAuthWebViewKt { *; }
-keepclassmembers class com.lightphone.spotify.playback.PlaybackController {
    *** completeLogin(...);
    *** mapSpotifyError(...);
}
